# Generated by Django 4.0.7 on 2022-08-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Fruit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, default=120, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default='Acme Inc', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.2, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Kg', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
